- Makefile
- components/global/portal/io.cellery.observability.ui/package-lock.json
- components/global/portal/io.cellery.observability.ui/package.json
- components/global/portal/io.cellery.observability.ui/pom.xml
- docker/portal/pom.xml
- docker/sp/pom.xml
- pom.xml
> Add Makefile and supporting changes to run a proper build
> Add support to do a proper build
> The Makefile with the relevant targets are added and updated the POMs to add SCM tags and proper changes to support the new Makefile.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> GNU Make 4.1
> JDK 1.8.0_192
> N/A
> Add Makefile

- Makefile
- docker/portal/pom.xml
- docker/sp/pom.xml
- pom.xml
> Add minor modifications in preparation for the release
> Prepare for the release 0.1.0
> Relevant POMs are modified in preparation for the release
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> Maven 3.5.4
> JDK 1.8.0_192
> N/A
> Add modifications for preparing for releases

- components/global/portal/io.cellery.observability.ui/src/components/App.js
- components/global/portal/io.cellery.observability.ui/src/components/SignIn.js
- components/global/portal/io.cellery.observability.ui/src/components/appLayout/MainAppBar.js
- components/global/portal/io.cellery.observability.ui/src/components/cells/component/ComponentDependencyGraph.js
- components/global/portal/io.cellery.observability.ui/src/components/common/DependencyGraph.js
- Updating theme
- Dependency graph UI improvements
> Observability Dashboard UI improvements

- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/Constants.java
- components/global/portal/io.cellery.observability.ui/package-lock.json
- pom.xml
> Add missing dependency version in root POM
> Add missing dependency version in root POM
> Add missing dependency version in root POM
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Add missing dependency version in root POM

- components/global/core/io.cellery.observability.api/pom.xml
- components/global/portal/io.cellery.observability.ui/src/components/SignIn.js
- pom.xml
Fix client id fetching issue in Observability-Portal.
> Fix client id fetching issue in Observability-Portal

- .travis.yml
- components/global/portal/io.cellery.observability.ui/package.json
- components/global/portal/io.cellery.observability.ui/pom.xml
- docker/sp/Dockerfile
- pom.xml
> Add Travis support and fix minor issues
> Validate PRs using Travis.
> Travis configuration is added to the repository. Minor changes such as changing "npm install" to "npm ci" had been done to make the build more CI/CD friendly. The Siddhi Store RDBMS version had been bumped as well to overcome a known concurrency issue in the previous version.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Add Travis

- components/global/portal/io.cellery.observability.ui/src/components/common/state/index.js
- components/global/portal/io.cellery.observability.ui/src/components/common/toptoolbar/DateRangePicker.js
- components/global/portal/io.cellery.observability.ui/src/components/common/toptoolbar/index.js
- components/global/portal/io.cellery.observability.ui/src/components/tracing/search/TracesList.js
- components/global/portal/io.cellery.observability.ui/src/components/tracing/view/SequenceDiagram.js
- components/global/portal/io.cellery.observability.ui/src/components/tracing/view/timeline/TimelineView.js
- components/global/portal/io.cellery.observability.ui/src/utils/tracing/span.js
> The sequence diagram fails in viewing traces with Web Cells because the algorithm of generating the actions and actors is not accurate. This needs to be fixed.
> Refactor and fix the Sequence Diagram to view Web Cells and Logic Cells.
> The Sequence Diagram was refactored and updated.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Refactor and fix Sequence Diagram

- components/global/core/io.cellery.observability.api/pom.xml
- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/auth/OIDCOauthManager.java
- docker/sp/pom.xml
- pom.xml
> Code has been refactored and replaced Unirest library (external library) with HttpPost (internal) for validating token by calling introspection endpoint.
> Refactor code and remove Unirest library

- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/Constants.java
- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/UserAuthenticationAPI.java
- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/auth/OIDCOauthManager.java
- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/interceptor/AuthInterceptor.java
- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/interceptor/CORSInterceptor.java
- components/global/portal/io.cellery.observability.ui/src/utils/api/httpUtils.js
- components/global/portal/io.cellery.observability.ui/src/utils/api/httpUtils.test.js
> Adding cookies to improve authentication of the Cellery Dashboard and authorization of observability backend APIs.
> Add cookies to improve API authorization

- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/AggregatedRequestsAPI.java
- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/interceptor/AuthInterceptor.java
- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/siddhi/SiddhiStoreQueryTemplates.java
- components/global/portal/io.cellery.observability.ui/src/components/cells/cell/Details.js
- components/global/portal/io.cellery.observability.ui/src/components/cells/cell/Metrics.js
- components/global/portal/io.cellery.observability.ui/src/components/cells/component/Details.js
- components/global/portal/io.cellery.observability.ui/src/components/cells/component/Metrics.js
- components/global/portal/io.cellery.observability.ui/src/components/overview/SidePanelContent.js
- components/global/portal/io.cellery.observability.ui/src/components/overview/index.js
- components/global/portal/io.cellery.observability.ui/src/utils/constants.js
> Update the Portal and API to make the Portal's health indicators to be more consistent.
> Give a consistent view of the system health to the users.
> The health indicator logic and API endpoints are updated accordingly to be more consistent. The unknown status is introduced to the overview for zero requests conditions.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> JDK 1.8.0_192
> N/A
> Update Portal to make the Health Indicators consistent

- .codecov.yml
- components/global/core/io.cellery.observability.k8s.client/pom.xml
- components/global/core/io.cellery.observability.k8s.client/src/test/resources/log4j.properties
- components/global/core/io.cellery.observability.k8s.client/src/test/resources/testng.xml
- components/global/core/io.cellery.observability.tracing.receiver/pom.xml
- components/global/core/io.cellery.observability.tracing.receiver/src/test/java/io/cellery/observability/tracing/receiver/internal/CodecTestCase.java
- components/global/core/io.cellery.observability.tracing.receiver/src/test/resources/log4j.properties
- components/global/core/io.cellery.observability.tracing.receiver/src/test/resources/testng.xml
- components/global/core/io.cellery.observability.tracing.synapse.handler/pom.xml
- components/global/core/io.cellery.observability.tracing.synapse.handler/src/main/java/io/cellery/observability/tracing/synapse/handler/Constants.java
- components/global/core/io.cellery.observability.tracing.synapse.handler/src/main/java/io/cellery/observability/tracing/synapse/handler/TracingSynapseHandler.java
- components/global/core/io.cellery.observability.tracing.synapse.handler/src/test/java/io/cellery/observability/tracing/synapse/handler/TracingSynapseHandlerTestCase.java
- components/global/core/io.cellery.observability.tracing.synapse.handler/src/test/resources/log4j.properties
- components/global/core/io.cellery.observability.tracing.synapse.handler/src/test/resources/testng.xml
- pom.xml
> Add Unit Tests for the Tracing Synapse Handler.
> Add Unit Tests for the Tracing Synapse Handler.
> Add Unit Tests for the Tracing Synapse Handler.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Add Tracing Synapse Handler Tests

- components/global/portal/io.cellery.observability.ui/src/components/tracing/view/SequenceDiagram.js
> Due to a bug in the Sequence Diagram the component level sequence diagram failed to render. 
> Fix bug in the component level sequence diagram.
> The relevant checks were added to ensure that the error conditions are properly handled
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Fix bug in Component Level Sequence Diagram rendering

- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/UserAuthenticationAPI.java
- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/auth/OIDCOauthManager.java
> Perform DCR while user logs in and resolves #46

- pom.xml
Update fabric8 k8s client version to 4.3.0
> Update fabric8 k8s client version to 4.3.0

- components/global/core/io.cellery.observability.model.generator/pom.xml
- components/global/core/io.cellery.observability.model.generator/src/main/java/io/cellery/observability/model/generator/ModelGenerationExtension.java
- components/global/core/io.cellery.observability.model.generator/src/main/java/io/cellery/observability/model/generator/ModelManager.java
- components/global/core/io.cellery.observability.model.generator/src/main/java/io/cellery/observability/model/generator/Node.java
- components/global/core/io.cellery.observability.model.generator/src/main/java/io/cellery/observability/model/generator/model/SpanInfo.java
- components/global/core/io.cellery.observability.model.generator/src/test/java/io/cellery/observability/model/generator/ModelGenTestCase.java
- components/global/core/io.cellery.observability.model.generator/src/test/resources/testng.xml
- components/global/core/io.cellery.observability.model.generator/src/test/resources/tracing-app.siddhi
- components/global/core/io.cellery.observability.siddhi.apps/src/main/siddhi/tracing-app.siddhi
- components/global/portal/io.cellery.observability.ui/src/components/App.js
- components/global/portal/io.cellery.observability.ui/src/components/cells/cell/CellDependencyView.js
- components/global/portal/io.cellery.observability.ui/src/components/cells/cell/ComponentList.js
- components/global/portal/io.cellery.observability.ui/src/components/cells/cell/Details.js
- components/global/portal/io.cellery.observability.ui/src/components/cells/component/ComponentDependencyView.js
- components/global/portal/io.cellery.observability.ui/src/components/cells/component/Details.js
- components/global/portal/io.cellery.observability.ui/src/components/overview/index.js
- components/global/portal/io.cellery.observability.ui/src/components/tracing/view/index.js
> Update Model Generator to the new tracing data format.
> Update Model Generator to the new tracing data format.
> Update Model Generator to the new tracing data format.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Update Model Generator to the new tracing data format

- components/global/core/io.cellery.observability.siddhi.apps/src/main/siddhi/istio-telemetry-app.siddhi
- components/global/core/io.cellery.observability.siddhi.apps/src/main/siddhi/k8s-pod-telemetry-app.siddhi
- components/global/portal/io.cellery.observability.ui/src/components/overview/index.js
> Add minor bug fixes
> Add minor bug fixes
> Add minor bug fixes
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> Depends on wso2-cellery/distribution#159
> N/A
> N/A
> N/A
> Fix bugs in metrics

- components/global/portal/io.cellery.observability.ui/src/components/SignIn.js
- components/global/portal/io.cellery.observability.ui/src/components/cells/component/ComponentDependencyGraph.js
- components/global/portal/io.cellery.observability.ui/src/components/cells/component/ComponentDependencyView.js
- Fix https://github.com/wso2-cellery/mesh-observability/issues/74
- Fix https://github.com/wso2-cellery/mesh-observability/issues/75 
- Position dependency diagram to fit screen size
> Fix component dependency graph issues

- components/global/portal/io.cellery.observability.ui/src/components/cells/cell/CellDependencyView.js
- components/global/portal/io.cellery.observability.ui/src/components/cells/component/ComponentDependencyGraph.js
- components/global/portal/io.cellery.observability.ui/src/components/cells/component/ComponentDependencyView.js
- Fix graph render issue on back button click
- Fix zoom in graph reset
> Component graph fixes

- components/global/core/io.cellery.observability.k8s.client/src/main/java/io/cellery/observability/k8s/client/Utils.java
> Add additional null checks for Cell/Composite watchers
> Add additional null checks for Cell/Composite watchers
> Add additional null checks for Cell/Composite watchers
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Add additional null checks for Cell/Composite watchers

- components/global/portal/io.cellery.observability.ui/src/components/overview/index.js
> Fix composite error node render issue
> Handle no ingress types scenario in diagram
> Fix composite error node render issue

- components/global/mixer-adapter/pkg/store/memory/memory.go
- components/global/mixer-adapter/pkg/store/memory/memory_test.go
> Fix issue when using memory persistence
> Fix issue when using memory persistence

- .travis.yml
- README.md
- components/global/core/io.cellery.observability.k8s.client/src/test/java/io/cellery/observability/k8s/client/BaseTestCase.java
- components/global/portal/io.cellery.observability.ui/package-lock.json
- components/global/portal/io.cellery.observability.ui/package.json
- pom.xml
> Update Repo links to reflect Repo move
> Update Repo links to reflect Repo move
> Update Repo links to reflect Repo move
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Update Repo links to reflect Repo move

- components/global/core/io.cellery.observability.siddhi.apps/src/main/siddhi/istio-telemetry-app.siddhi
- components/global/core/io.cellery.observability.siddhi.apps/src/main/siddhi/telemetry-app.siddhi
- components/global/core/io.cellery.observability.siddhi.apps/src/main/siddhi/tracing-app.siddhi
- components/global/core/io.cellery.observability.telemetry.deduplicator/pom.xml
- components/global/core/io.cellery.observability.telemetry.deduplicator/src/main/java/io/cellery/observability/telemetry/deduplicator/DeduplicationStreamProcessor.java
- components/global/core/io.cellery.observability.telemetry.deduplicator/src/main/java/io/cellery/observability/telemetry/deduplicator/DeduplicationWindowExtension.java
- components/global/core/io.cellery.observability.telemetry.deduplicator/src/main/java/io/cellery/observability/telemetry/deduplicator/internal/Constants.java
- components/global/core/pom.xml
- docker/sp/pom.xml
- pom.xml
> Remove duplications of the metrics received by Istio
> Write a Siddhi custom window to wait for duplications.
> Add telemetry deduplicator

- .gitignore
- Makefile
- components/global/observability-agent/cmd/telemetry-agent/main.go
- components/global/observability-agent/cmd/tracing-agent/main.go
- components/global/observability-agent/pkg/adapter/adapter_test.go
- components/global/observability-agent/pkg/config/config.go
- components/global/observability-agent/pkg/publisher/publisher.go
- components/global/observability-agent/pkg/publisher/publisher_test.go
- components/global/observability-agent/pkg/store/database/database.go
- components/global/observability-agent/pkg/store/database/database_test.go
- components/global/observability-agent/pkg/store/file/file.go
- components/global/observability-agent/pkg/store/file/file_test.go
- components/global/observability-agent/pkg/store/memory/memory.go
- components/global/observability-agent/pkg/store/memory/memory_test.go
- components/global/observability-agent/pkg/writer/writer.go
- components/global/observability-agent/pkg/writer/writer_test.go
- components/global/observability-agent/test/e2e/adapter_integration_test.go
- go.mod
Refactor go module to cellery.io/cellery-observability
> Refactor go module to cellery.io/cellery-observability

- components/global/portal/io.cellery.observability.ui/node-server/config/portal.json
- components/global/portal/io.cellery.observability.ui/src/components/appLayout/MainAppBar.js
> Current observability implementation does not support SSO login flow.
> Added user information in the portal UI.
> Enable SSO login flow

- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/interceptor/AuthInterceptor.java
- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/interceptor/CORSInterceptor.java
- components/global/core/io.cellery.observability.api/src/main/java/io/cellery/observability/api/internal/ApiServiceComponent.java
- components/global/core/io.cellery.observability.api/src/test/resources/conf/deployment.yaml
- components/global/core/io.cellery.observability.auth/pom.xml
- components/global/core/io.cellery.observability.auth/src/main/java/io/cellery/observability/auth/CelleryLocalAuthProvider.java
- components/global/core/io.cellery.observability.auth/src/main/java/io/cellery/observability/auth/DcrProvider.java
- components/global/core/io.cellery.observability.auth/src/main/java/io/cellery/observability/auth/internal/AuthConfig.java
- components/global/core/io.cellery.observability.auth/src/main/java/io/cellery/observability/auth/internal/AuthServiceComponent.java
- components/global/core/io.cellery.observability.auth/src/test/java/io/cellery/observability/auth/AuthConfigTestCase.java
- components/global/core/io.cellery.observability.auth/src/test/resources/conf/deployment.yaml
- components/global/core/io.cellery.observability.model.generator/src/main/java/io/cellery/observability/model/generator/ModelAddEdgeStreamProcessor.java
- components/global/core/io.cellery.observability.model.generator/src/main/java/io/cellery/observability/model/generator/ModelAddNodeStreamProcessor.java
- components/global/core/io.cellery.observability.model.generator/src/main/java/io/cellery/observability/model/generator/ModelRemoveNodeStreamProcessor.java
- components/global/core/io.cellery.observability.model.generator/src/main/java/io/cellery/observability/model/generator/internal/ModelStoreManager.java
- components/global/core/io.cellery.observability.model.generator/src/main/java/io/cellery/observability/model/generator/model/ModelManager.java
- components/global/portal/io.cellery.observability.ui/node-server/config/portal.json
- components/global/portal/io.cellery.observability.ui/src/components/common/state/stateHolder.js
- components/global/portal/io.cellery.observability.ui/src/components/instances/component/K8sPodsList.js
- components/global/portal/io.cellery.observability.ui/src/utils/constants.js
> Make the Local Runtime ID configurable
> Make the Local Runtime ID configurable
> Make the Local Runtime ID configurable
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> wso2/cellery-distribution#205
> N/A
> N/A
> N/A
> Make the Local Runtime ID configurable

- docker/kube-agent/Dockerfile
- docker/telemetry-agent/Dockerfile
- docker/tracing-agent/Dockerfile
Add ca certificates to the scratch docker images
> Add ca certificates to the scratch docker images

- docker/sp/pom.xml
- pom.xml
> Remove redundant dependency

- components/global/portal/io.cellery.observability.ui/src/components/overview/index.js
> Fix overview ingress types bug
> Fix overview ingress types bug
> Fix overview ingress types bug
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Fix overview ingress types bug
